# Generated by Django 5.0.2 on 2024-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='slider_img',
            field=models.ImageField(blank=True, null=True, upload_to='Slider/'),
        ),
    ]
